### ISSUE TITLE
Is frequency / number of bus data available?

### ISSUE THREAD

**Issue by rtmilton** [vgXhc/metro_boardings#1]
Thanks for making this! I know its kind of old but I was (re)visiting it in looking at the newest version of the redesign plan. It is difficult to compare ridership across stops when I know that some stops have more buses serving them than others. It would be cool to have ridership per bus or a similar measure. But I guess what we'd want is pre-pandemic frequencies. Is there even a source for old schedules were we to want to do it by hand? Anyway, thanks for making this!

**Comment by vgXhc** [comment]
To get the number of buses at each stop, you'd need

1. a pre-pandemic GTFS schedule file
2. code to parse that data in the way you want

The former appears to be available via [OpenMobilityData](https://openmobilitydata.org/p/metro-transit-madison/181). For the latter, I'm not super proficient with GTFS data, but number of buses at a given stop I think is not that hard. I'm sure Metro keeps pdfs of their old Riders' Guides, but doing it by hand sounds like a lot of work. I'm pretty busy at the moment, but I'll see if I find some time to play around with the old GTFS file.

**Comment by vgXhc** [comment]
Looks like the `tidytransit` package should make this relatively easy. See this [vignette](https://cran.r-project.org/web/packages/tidytransit/vignettes/frequency.html). I'll give it a try.

**Comment by vgXhc** [comment]
We're getting somewhere. @rtmilton Is this roughly what you had in mind? I still need to do some checks on whether I got it right, but these are the number of boardings divided by the number of buses at a stop on a Wednesday in Feb 2020. Suddenly the transfer points become much less prominent.
![image](https://user-images.githubusercontent.com/11335221/156672922-f7723f16-4029-4767-b151-255bc1bc1535.png)

**Comment by rtmilton** [comment]
Yes, this is awesome! I think it's a better measure of transit demand. Its
not possible to perfectly account for what usage would be like if there was
equal service everywhere but I think it's a bit closer than just total
boardings. Thanks!

**Comment by vgXhc** [comment]
Okay, great, I'll finish this up and publish a new article with an interactive map in the next couple days. As you said, it's tricky to define transit demand on boardings alone, but the amount of service of course also is partly because there already is demand but then also creates additional demand. And so on...

**Comment by vgXhc** [comment]
New post with maps is up. Curious what you make of the numbers. https://haraldkliems.netlify.app/posts/boardings-per-bus-per-stop-a-useful-metric/

**Comment by rtmilton** [comment]
Awesome, thanks for throwing this together. I'm not totally sure this
measure is super useful in and of itself, I certainly wouldn't want to
blindly base policy on it -- but if nothing else it's nice to have the
ridership numbers along with the bus numbers on the same map/dataset. It is
interesting to look at outliers in their relationship, like in the
scatterplot below.

I do think you can draw some conclusions. Some stops may be underserved.
Some of the highly used campus stops really don't have many buses. Some
stops outside of the downtown core also have high riders/bus, but they
aren't near other underserved stops, making them difficult to serve. These
are either apartment complexes (like Offshore & Yellowstone), suburban
employers, or the Sun Prairie P&R. This highlights the need for smarter
development.

Some of the areas that would lose service under the 'ridership' alternative
have very few buses with very few riders. Even the well used stops have,
what seems to me, pretty bad bus service. It would be interesting to see
how that and the riders/bus compare to other cities.


[image: image.png]
